#!/bin/bash

cd _build/default

if [ -e test/$1.mli ] ; then
  echo "::: test/$1.mli :::"
  .ppx/ppx_deriving.std+ppx_deriving_dynt+ppx_expect/ppx.exe \
    --cookie 'library-name="test"' \
    --intf test/$1.mli -corrected-suffix .ppx-corrected -diff-cmd - \
    | ocp-indent
fi

if [ -e test/$1.ml ] ; then
  echo "::: test/$1.ml ::::"

  .ppx/ppx_deriving.std+ppx_deriving_dynt+ppx_expect/ppx.exe \
    --cookie 'library-name="test"' \
    --impl test/$1.ml -corrected-suffix .ppx-corrected -diff-cmd -\
    | ocp-indent
fi
